# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'raft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\"<\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\x0c\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"b\n\x12RequestVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x61ndidateId\x18\x02 \x01(\x05\x12\x14\n\x0clastLogIndex\x18\x03 \x01(\x03\x12\x13\n\x0blastLogTerm\x18\x04 \x01(\x03\"8\n\x13RequestVoteResponse\x12\x13\n\x0bvoteGranted\x18\x01 \x01(\x08\x12\x0c\n\x04term\x18\x02 \x01(\x05\"\x98\x01\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x10\n\x08leaderId\x18\x02 \x01(\x05\x12\x14\n\x0cprevLogIndex\x18\x03 \x01(\x03\x12\x13\n\x0bprevLogTerm\x18\x04 \x01(\x03\x12\x1f\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x0e.raft.LogEntry\x12\x14\n\x0cleaderCommit\x18\x06 \x01(\x03\"J\n\x15\x41ppendEntriesResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x12\n\nmatchIndex\x18\x03 \x01(\x03\"2\n\x10HeartbeatRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x10\n\x08leaderId\x18\x02 \x01(\x05\"2\n\x11HeartbeatResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\" \n\rStatusRequest\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\"[\n\x0eStatusResponse\x12\r\n\x05state\x18\x01 \x01(\t\x12\x14\n\x0c\x63urrent_term\x18\x02 \x01(\x05\x12\x11\n\tlog_count\x18\x03 \x01(\x05\x12\x11\n\tis_leader\x18\x04 \x01(\x08\x32\x8e\x02\n\x0bRaftService\x12\x33\n\x06Status\x12\x13.raft.StatusRequest\x1a\x14.raft.StatusResponse\x12\x42\n\x0bRequestVote\x12\x18.raft.RequestVoteRequest\x1a\x19.raft.RequestVoteResponse\x12H\n\rAppendEntries\x12\x1a.raft.AppendEntriesRequest\x1a\x1b.raft.AppendEntriesResponse\x12<\n\tHeartbeat\x12\x16.raft.HeartbeatRequest\x1a\x17.raft.HeartbeatResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGENTRY']._serialized_start=20
  _globals['_LOGENTRY']._serialized_end=80
  _globals['_REQUESTVOTEREQUEST']._serialized_start=82
  _globals['_REQUESTVOTEREQUEST']._serialized_end=180
  _globals['_REQUESTVOTERESPONSE']._serialized_start=182
  _globals['_REQUESTVOTERESPONSE']._serialized_end=238
  _globals['_APPENDENTRIESREQUEST']._serialized_start=241
  _globals['_APPENDENTRIESREQUEST']._serialized_end=393
  _globals['_APPENDENTRIESRESPONSE']._serialized_start=395
  _globals['_APPENDENTRIESRESPONSE']._serialized_end=469
  _globals['_HEARTBEATREQUEST']._serialized_start=471
  _globals['_HEARTBEATREQUEST']._serialized_end=521
  _globals['_HEARTBEATRESPONSE']._serialized_start=523
  _globals['_HEARTBEATRESPONSE']._serialized_end=573
  _globals['_STATUSREQUEST']._serialized_start=575
  _globals['_STATUSREQUEST']._serialized_end=607
  _globals['_STATUSRESPONSE']._serialized_start=609
  _globals['_STATUSRESPONSE']._serialized_end=700
  _globals['_RAFTSERVICE']._serialized_start=703
  _globals['_RAFTSERVICE']._serialized_end=973
# @@protoc_insertion_point(module_scope)
